Changes to make the repo session-aware
Cimpress/cimpress-customizr pull request #26
Opened 2021-05-20 09:56 UTC by Rahul-Nahar-1992

Adding the ability to proxy requests via Session API in case sessionId was provided instead of an accessToken.

2021-05-20 10:52 UTC, lholota approved these changes

2021-05-20 13:59 UTC, thoean requested changes
Can you undo the formatting changes (whitespaces added where there weren't). If we want to change the formatting in this repository, we should do that as a separate MR.

You'll also need to increase the version in `package.json`, not only in the readme file.

2021-05-20 14:32 UTC, Rahul-Nahar-1992 commented
Hey @thoean, I have undone the formatting changes!

The `package.json` is already updated with the increased version (1.1.14).

2021-05-20 14:59 UTC, thoean commented
Great, thanks. Ivan and Igor will take it from there who know the inner details of this change better.

2021-05-21 10:31 UTC, istanishev commented on CHANGELOG.md
> +## [1.1.14] - 2021.05.19
Likely this should be 1.2.0 as it is adding a new feature.

2021-05-21 10:34 UTC, istanishev approved these changes

2021-05-21 12:00 UTC, merged